;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Attack.Bear",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.Player",DevComment="")
+GameplayTagList=(Tag="Ability.Death.Bear",DevComment="")
+GameplayTagList=(Tag="Ability.Death.Player",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Event.Death",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")

